RegistrationTest_v01: Course Class Reference
Course Class Reference
Holds information about courses for student res.
#include <course.H>
Public Member Functions
Course ()
Default constructor.
Course (const char *nam, char sect, unsigned cred)
Construct a course from a name, section letter and number of credits.
unsigned GetCredits () const
Accessor method for credits.
void SetCredits (unsigned cred)
Mutator method for cred.
Friends
ostream & operator<< (ostream &os, const Course &C)
Overload operator << for file output.
istream & operator >> (istream &input, Course &C)
Overload operator >> for file input.
Detailed Description
Holds information about courses for student res.
Author
KRI
Version
01
Author
smr
Version
02
Author
Jordan Smith
Version
03
Date
06/03/2019 Jordan Smith, further expand on design.
Todo:
update all comments and indentation.
Bug:
None known
Definition at line 29 of file course.H.
Constructor & Destructor Documentation
Course() [1/2]
Course::Course ()
Default constructor.
Parameters
nil
Returns
Course
Definition at line 5 of file course.CPP.
 {
   name[0] = '\0'; // it is a char * string, not a C++ string object.
 }
Course() [2/2]
Course::Course (const char * nam, char sect, unsigned cred)
Construct a course from a name, section letter and number of credits.
Parameters
nam const: char *
sect char
cred unsigned
Returns
Registration
Definition at line 10 of file course.CPP.
 {
   strncpy( name, nam, CourseNameSize );
   section = sect;
   credits = cred;
 }
Referenced by main().
Member Function Documentation
GetCredits()
unsigned Course::GetCredits () const inline
Accessor method for credits.
Parameters
nil
Returns
const: unsigned
Definition at line 98 of file course.H.
 {
     return credits;
 }
Referenced by Registration::GetCredits().
SetCredits()
void Course::SetCredits (unsigned cred) inline
Mutator method for cred.
Parameters
cred unsigned
Returns
void
Definition at line 103 of file course.H.
 {
     credits = cred;
 }
Referenced by main().
Friends And Related Function Documentation
operator >>
istream& operator >> (istream & input, Course & C) friend
Overload operator >> for file input.
Parameters
input istream &
C Course &
Returns
istream &
Definition at line 18 of file course.CPP.
 {
   input >> C.name >> C.section >> C.credits;
   return input;
 }
Referenced by operator >>().
operator<<
ostream& operator<< (ostream & os, const Course & C) friend
Overload operator << for file output.
Parameters
os ostream &
C const: Course &
Returns
ostream &
Definition at line 24 of file course.CPP.
 {
   os << "  Course:  " << C.name << '\n'
      << "  Section: " << C.section << '\n'
      << "  Credits: " << C.credits << '\n';
   return os;
 }
The documentation for this class was generated from the following files:
C:/Users/jorda/Desktop/ICT283/Topic02/Practical/registration-code/registrationTest_V01/course.H
C:/Users/jorda/Desktop/ICT283/Topic02/Practical/registration-code/registrationTest_V01/course.CPP