RegistrationTest_v01: Registration Class Reference
Registration Class Reference
Holds information about a student's registration at university.
#include <regist.H>
Public Member Functions
Registration ()
Default constructor. Sets values to 0.
unsigned GetCredits () const
Accessor method for credits.
unsigned GetCount () const
Accessor method for count, sums all credits in array of courses.
Friends
ostream & operator<< (ostream &os, const Registration &R)
Overloaded operator for file output.
istream & operator >> (istream &input, Registration &R)
Overloaded operator for file input.
Detailed Description
Holds information about a student's registration at university.
Author
KRI
Version
01
Author
smr
Version
02
Author
Jordan Smith
Version
03
Date
06/03/2019 Jordan Smith, further expand on design.
Todo:
Bug:
None known
Definition at line 32 of file regist.H.
Constructor & Destructor Documentation
Registration()
Registration::Registration ()
Default constructor. Sets values to 0.
Parameters
nil
Returns
Registration
Definition at line 5 of file regist.CPP.
 {
     studentId = 0;
     semester = 0;
     count = 0;
 }
Member Function Documentation
GetCount()
unsigned Registration::GetCount () const inline
Accessor method for count, sums all credits in array of courses.
Parameters
nil
Returns
unsigned const
Definition at line 95 of file regist.H.
 {
   return count;
 }
Referenced by main().
GetCredits()
unsigned Registration::GetCredits () const
Accessor method for credits.
Parameters
nil
Returns
unsigned const
Definition at line 12 of file regist.CPP.
 {
     unsigned sum = 0;
     for(unsigned i = 0; i < count; i++)
     {
         sum += courses[i].GetCredits();
     }
     return sum;
 }
References Course::GetCredits().
Referenced by main().
Friends And Related Function Documentation
operator >>
istream& operator >> (istream & input, Registration & R) friend
Overloaded operator for file input.
Parameters
input istream pointer
R registration object
Returns
friend istream pointer
Definition at line 24 of file regist.CPP.
 {
     input >> R.studentId >> R.semester >> R.count;
     for(unsigned i = 0; i < R.count; i++)
     {
         input >> R.courses[i];
     }
     return input;
 }
Referenced by main().
operator<<
ostream& operator<< (ostream & os, const Registration & R) friend
Overloaded operator for file output.
Parameters
os ostream pointer
R registration object
Returns
friend ostream pointer
Definition at line 36 of file regist.CPP.
 {
     os << "Student ID: " << R.studentId << endl
     << "Semester:   " << R.semester << endl;
     for(unsigned i = 0; i < R.count; i++)
     {
         os << R.courses[i] << endl;
     }
     return os;
 }
The documentation for this class was generated from the following files:
C:/Users/jorda/Desktop/ICT283/Topic02/Practical/registration-code/registrationTest_V01/regist.H
C:/Users/jorda/Desktop/ICT283/Topic02/Practical/registration-code/registrationTest_V01/regist.CPP