RegistrationTest_v01: C:/Users/jorda/Desktop/ICT283/Topic02/Practical/registration-code/registrationTest_V01/registrationTest_v01.CPP File Reference
registrationTest_v01.CPP File Reference
#include <iostream>
#include <fstream>
#include "course.h"
#include "regist.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 20 of file registrationTest_v01.CPP.
 {
   ifstream infile( "rinput.txt" );
   if( !infile ) return -1;
   Registration R;
   infile >> R;
   ofstream ofile( "routput.txt" );
 // Use a debugger and track down the calls made "behind the scene"
   ofile << R
     << "Number of courses = " << R.GetCount() << '\n'
     << "Total credits     = " << R.GetCredits() << '\n';
   // Declare and initialize a Course, and modify
   // its credits.
   Course aCourse( "MTH_3020", 'B', 2 );
   aCourse.SetCredits( 5 );
   cout << aCourse << endl; // the operator << for Course is called
   return 0;
 }
References Course::Course(), Registration::GetCount(), Registration::GetCredits(), Registration::operator >>, and Course::SetCredits().